Repository milvus-io/milvus-sdk-rust, pull requests merged in 2023-03, with the labels that each got.

#37 Add delete entities api and impl `Clone` for Client
  src/client.rs
  src/collection.rs
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, lgtm, size/S

#39 Update mergify rule
  .github/mergify.yml
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, size/XS

#40 Refine create_collection method
  examples/collection.rs
  src/client.rs
  src/lib.rs
  src/options.rs
  tests/client.rs
  tests/common/mod.rs
Labels: ci-passed, dco-passed, lgtm, kind/improvement, size/L
