Repository milvus-io/milvus-sdk-rust, pull requests merged in 2023-05, with the labels that each got.

#45 [Bug] fix the wrong dtype
  src/schema.rs
Labels: ci-passed, dco-passed, size/XS

#54 Add OWNERS file
  OWNERS
Labels: dco-passed, kind/improvement, size/XS

#57 Fix warnings
  src/client.rs
  src/collection.rs
  src/proto/mod.rs
  src/utils.rs
Labels: ci-passed, dco-passed, approved, lgtm, kind/improvement, size/M

#58 Update README
  Cargo.toml
  README.md
  examples/collection.rs
Labels: dco-passed, approved, lgtm, kind/improvement, size/M

#56 Add drop_partition,release_partitions,load_partitions
  src/client.rs
  src/collection.rs
  tests/client.rs
  tests/collection.rs
Labels: ci-passed, dco-passed, approved, lgtm, size/L
