Repository milvus-io/milvus-sdk-rust, pull requests merged in 2024-01, with the labels that each got.

#80 impl delete back
  build.rs
  examples/collection.rs
  src/client.rs
  src/collection.rs
  src/data.rs
  src/error.rs
  src/lib.rs
  src/mutate.rs
  src/options.rs
  src/partition.rs
  src/proto/mod.rs
  src/query.rs
  src/types.rs
  src/value.rs
  tests/alias.rs
  tests/client.rs
  tests/collection.rs
  tests/common/mod.rs
Labels: ci-passed, dco-passed, approved, lgtm, kind/improvement, size/XL

#82 improvement: upgrade the CI Milvus to latest master
  docker-compose.yml
Labels: ci-passed, dco-passed, approved, lgtm, kind/improvement, size/S

#81 Add manual compaction method
  src/client.rs
  src/collection.rs
  tests/collection.rs
Labels: ci-passed, dco-passed, approved, lgtm, kind/improvement, size/M

#84 Add upsert
  src/mutate.rs
  tests/alias.rs
  tests/client.rs
  tests/collection.rs
  tests/common/mod.rs
Labels: ci-passed, dco-passed, approved, lgtm, size/L

#85 add range_search test
  tests/collection.rs
Labels: ci-passed, dco-passed, approved, lgtm, kind/improvement, size/M
